-- 1) doctor tablosu
CREATE TABLE IF NOT EXISTS public.doctor
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100),
    surname character varying(100),
    proficiency character varying(100),
    CONSTRAINT doctor_pkey PRIMARY KEY (id)
);

-- 2) nurse tablosu
CREATE TABLE IF NOT EXISTS public.nurse
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100),
    surname character varying(100),
    proficiency character varying(100),
    CONSTRAINT nurse_pkey PRIMARY KEY (id)
);

-- 3) patient tablosu
CREATE TABLE IF NOT EXISTS public.patient
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100),
    surname character varying(100),
    email character varying(150),
    complaint text,
    CONSTRAINT patient_pkey PRIMARY KEY (id)
);

-- 4) surgery tablosu
CREATE TABLE IF NOT EXISTS public.surgery
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nurse_id bigint,
    patient_id bigint,
    doctor_id bigint,
    CONSTRAINT surgery_pkey PRIMARY KEY (id),
    CONSTRAINT surgery_nurse_fk FOREIGN KEY (nurse_id) REFERENCES public.nurse (id),
    CONSTRAINT surgery_patient_fk FOREIGN KEY (patient_id) REFERENCES public.patient (id),
    CONSTRAINT surgery_doctor_fk FOREIGN KEY (doctor_id) REFERENCES public.doctor (id)
);

-- 5) operation tablosu
CREATE TABLE IF NOT EXISTS public.operation
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    patient_id bigint,
    doctor_id bigint,
    CONSTRAINT operation_pkey PRIMARY KEY (id),
    CONSTRAINT operation_patient_fk FOREIGN KEY (patient_id) REFERENCES public.patient (id),
    CONSTRAINT operation_doctor_fk FOREIGN KEY (doctor_id) REFERENCES public.doctor (id)
);

-- Örnek veriler
INSERT INTO doctor(name, surname, proficiency) VALUES ('Ayşe', 'Yılmaz', 'Cardiology');
INSERT INTO nurse(name, surname, proficiency) VALUES ('Elif', 'Kaya', 'Cardiology');
INSERT INTO patient(name, surname, email, complaint) VALUES ('Mehmet', 'Demir', 'mehmet@test.com', 'Göğüs ağrısı');
INSERT INTO surgery(nurse_id, patient_id, doctor_id) VALUES (1, 1, 1);
INSERT INTO operation(patient_id, doctor_id) VALUES (1, 1);
